name: Build BCC Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-android:
    name: Build BCC for Android
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Verify project structure
        run: |
          echo "Project structure:"
          ls -la
          echo "Checking required files:"
          test -f main.py && echo "✓ main.py exists" || echo "✗ main.py missing"
          test -d Pages && echo "✓ Pages directory exists" || echo "✗ Pages directory missing"
          test -f buildozer.spec && echo "✓ buildozer.spec exists" || echo "✗ buildozer.spec missing"
          echo "Checking Page files:"
          test -f Pages/Page1.kv && echo "✓ Page1.kv exists" || echo "✗ Page1.kv missing"
          test -f Pages/Page2.kv && echo "✓ Page2.kv exists" || echo "✗ Page2.kv missing"
          test -f Pages/Page3.kv && echo "✓ Page3.kv exists" || echo "✗ Page3.kv missing"
          test -f Pages/Page4.kv && echo "✓ Page4.kv exists" || echo "✗ Page4.kv missing"
          echo "Checking for CEET.png:"
          test -f CEET.png && echo "✓ CEET.png exists" || echo "✗ CEET.png missing"
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          pip install cython==0.29.33
          
      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: ~/.buildozer
          key: buildozer-${{ hashFiles('buildozer.spec') }}
          
      - name: Cache Buildozer dependencies
        uses: actions/cache@v3
        with:
          path: ./.buildozer
          key: buildozer-deps-${{ hashFiles('buildozer.spec') }}
          
      - name: Build with Buildozer
        env:
          BUILDOZER_LOG_LEVEL: 2
        run: |
          buildozer android debug
          
      - name: Find APK file
        id: find_apk
        run: |
          APK_PATH=$(find . -name "*.apk" -type f | head -1)
          echo "APK found at: $APK_PATH"
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
          
      - name: Rename APK
        run: |
          if [ -f "${{ steps.find_apk.outputs.apk_path }}" ]; then
            mv "${{ steps.find_apk.outputs.apk_path }}" "BCC-Control-v1.0.apk"
            echo "APK renamed to BCC-Control-v1.0.apk"
          fi
          
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: BCC-Android-APK
          path: "BCC-Control-v1.0.apk"
          retention-days: 30
          
      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            .buildozer/
            buildozer.log
          retention-days: 7
          
      - name: Display APK info
        if: success()
        run: |
          echo "✅ Build successful!"
          echo "APK size: $(du -h BCC-Control-v1.0.apk | cut -f1)"
          echo "APK created: BCC-Control-v1.0.apk"
